import mongoose from 'mongoose';

const globalSettingsSchema = new mongoose.Schema(
    {
        companyName: { type: String, required: true, default: 'Appzeto' },
        email: { type: String, required: true, default: 'admin@appzeto.com' },
        phone: {
            countryCode: { type: String, default: '+91' },
            number: { type: String, default: '' }
        },
        address: { type: String, default: '' },
        state: { type: String, default: '' },
        pincode: { type: String, default: '' },
        region: { type: String, default: 'India' },
        logo: {
            url: { type: String, default: '' },
            publicId: { type: String, default: '' }
        },
        favicon: {
            url: { type: String, default: '' },
            publicId: { type: String, default: '' }
        },
        themeColor: { type: String, default: '#0a0a0a' },
        modules: {
            food: { type: Boolean, default: true },
            homeBakery: { type: Boolean, default: false },

            quickCommerce: { type: Boolean, default: true },
            dudhwala: { type: Boolean, default: true },
        },
        codEnabled: { type: Boolean, default: true },
        onlinePaymentEnabled: { type: Boolean, default: true },
        showLocationPopup: { type: Boolean, default: true },
        bannedNumbers: { type: [String], default: [] },
        landingPage: {
            heroHeadline: { type: String, default: "India’s #1 food delivery app" },
            heroSubtitle: { type: String, default: "Experience fast & easy online ordering on the Minutekart app" },
            heroBgImage: { type: String, default: "/images/hero_bg.png" },
            heroBgVideo: { type: String, default: "" },
            playStoreUrl: { type: String, default: "#get-app-section" },
            googlePlayUrl: { type: String, default: "#get-app-section" },
            appStoreUrl: { type: String, default: "#get-app-section" },
            qrCodeImage: { type: String, default: "" },
            qrCodeHeadline: { type: String, default: "Download the app now!" },
            qrCodeSubtitle: { type: String, default: "Experience seamless online ordering only on the Minutekart app" },
            qrCodeText: { type: String, default: "Scan the QR code to download the app" },
            restaurantsCount: { type: String, default: "3,00,000+" },
            citiesCount: { type: String, default: "800+" },
            ordersCount: { type: String, default: "3 billion+" },
            ordersDeliveredCount: { type: String, default: "3 billion+" },
            sec2Headline: { type: String, default: "Better food for more people" },
            sec2Subtitle: { type: String, default: "For over a decade, we’ve enabled our customers to discover new tastes, delivered right to their doorstep" },
            section2Headline: { type: String, default: "Better food for more people" },
            section2Subtitle: { type: String, default: "For over a decade, we’ve enabled our customers to discover new tastes, delivered right to their doorstep" },
            sec3Headline: { type: String, default: "What’s waiting for you on the app?" },
            sec3Subtitle: { type: String, default: "Our app is packed with features that enable you to experience food delivery like never before" },
            section3Headline: { type: String, default: "What’s waiting for you on the app?" },
            section3Subtitle: { type: String, default: "Our app is packed with features that enable you to experience food delivery like never before" },
            userAppTitle: { type: String, default: "minutekart user" },
            userAppDesc: { type: String, default: "Get the app now to start ordering your favorite food & groceries!" },
            userAppDescription: { type: String, default: "Get the app now to start ordering your favorite food & groceries!" },
            userAppIcon: { type: String, default: "/images/minutekart_user.png" },
            userAppLink: { type: String, default: "/food/user" },
            userAppUrl: { type: String, default: "/food/user" },
            restaurantAppTitle: { type: String, default: "minutekart restaurant" },
            restaurantAppDesc: { type: String, default: "Partner with us to grow your restaurant business & manage orders!" },
            restaurantAppDescription: { type: String, default: "Partner with us to grow your restaurant business & manage orders!" },
            restaurantAppIcon: { type: String, default: "/images/minutekart_partner.png" },
            restaurantAppLink: { type: String, default: "/seller" },
            restaurantAppUrl: { type: String, default: "/seller" },
            sellerAppTitle: { type: String, default: "minutekart seller" },
            sellerAppDesc: { type: String, default: "Join as a local shop & instant grocery seller partner!" },
            sellerAppDescription: { type: String, default: "Join as a local shop & instant grocery seller partner!" },
            sellerAppIcon: { type: String, default: "/images/minutekart_partner.png" },
            sellerAppLink: { type: String, default: "/seller" },
            sellerAppUrl: { type: String, default: "/seller" },
            deliveryAppTitle: { type: String, default: "minutekart delivery" },
            deliveryAppDesc: { type: String, default: "Deliver with Minutekart & earn flexible daily income!" },
            deliveryAppDescription: { type: String, default: "Deliver with Minutekart & earn flexible daily income!" },
            deliveryAppIcon: { type: String, default: "/images/minutekart_delivery.png" },
            deliveryAppLink: { type: String, default: "#" },
            deliveryAppUrl: { type: String, default: "#" },

            // Footer Links, Social & Legal Settings
            footerCopyright: { type: String, default: "2008-2026 © Minutekart™ Ltd. All rights reserved." },
            footerDisclaimer: { type: String, default: "By continuing past this page, you agree to our Terms of Service, Cookie Policy, Privacy Policy and Content Policies. All trademarks are properties of their respective owners." },
            socialLinkedin: { type: String, default: "#" },
            socialInstagram: { type: String, default: "#" },
            socialYoutube: { type: String, default: "#" },
            socialFacebook: { type: String, default: "#" },
            socialTwitter: { type: String, default: "#" },
            socialItems: [{ platform: { type: String, default: "" }, url: { type: String, default: "" } }],
            col1Title: { type: String, default: "Eternal" },
            col2Title: { type: String, default: "For Restaurants" },
            col3Title: { type: String, default: "For Delivery Partners" },
            col4Title: { type: String, default: "Learn More" },
            col5Title: { type: String, default: "Social Links" },
            col1Items: [{ title: { type: String, default: "" }, url: { type: String, default: "" } }],
            col2Items: [{ title: { type: String, default: "" }, url: { type: String, default: "" } }],
            col3Items: [{ title: { type: String, default: "" }, url: { type: String, default: "" } }],
            col4Items: [{ title: { type: String, default: "" }, url: { type: String, default: "" } }],
            linkMinutekart: { type: String, default: "/food/user" },
            linkQuickCommerce: { type: String, default: "/quick" },
            linkDudhwala: { type: String, default: "/dudhwala" },
            linkHyperpure: { type: String, default: "/seller" },
            linkFeedingIndia: { type: String, default: "#" },
            linkInvestorRelations: { type: String, default: "#" },
            linkPartnerRestaurant: { type: String, default: "/seller" },
            linkAppsRestaurant: { type: String, default: "/seller/auth" },
            linkConsultingRestaurant: { type: String, default: "/seller" },
            linkPartnerDelivery: { type: String, default: "#" },
            linkAppsDelivery: { type: String, default: "#" },
            linkPrivacy: { type: String, default: "/profile/privacy" },
            linkSecurity: { type: String, default: "/profile/terms" },
            linkTerms: { type: String, default: "/profile/terms" },
            linkHelp: { type: String, default: "/profile/support" },
            linkReportFraud: { type: String, default: "#" },
            linkBlog: { type: String, default: "#" }
        }
    },
    { timestamps: true }
);

// We keep the collection name the same if we want to preserve data, 
// or rename it if we want a fresh start. 
// Given the user wants to "move" them, keeping data is likely preferred.
export const GlobalSettings = mongoose.model('GlobalSettings', globalSettingsSchema, 'common_global_settings');
